# Disable idiomatic version files to avoid mise warnings
[settings]
enable_idiomatic_version_files = false

# Set the Node.js version explicitly
[env]
NODE_VERSION = "20.10.0"

[tools]
node = { version = "20.10.0" } 