# .pages.yml - Cloudflare Pages configuration
build:
  command: npm run cloudflare-build
  output: build/client
  cwd: .
  environment:
    NODE_VERSION: "20.10.0"

compatibility_flags:
  - nodejs_compat 