[build]
  command = "npm install --force --legacy-peer-deps && npm install --no-save @remix-run/dev vite @remix-run/react && npm run netlify-force-build"
  publish = "build/client"
  ignore_errors = false
  
[build.environment]
  NODE_VERSION = "20.10.0"
  NPM_VERSION = "10.2.3"
  CI = "false"
  NODE_ENV = "production"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NPM_FLAGS = "--no-audit --no-fund --legacy-peer-deps"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Handle asset caching
[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable" 