[build]
  command = "CI=false npm run netlify-build:cjs"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "20.10.0"
  NPM_VERSION = "10.2.3"
  CI = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Handle asset caching
[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable" 